### ISSUE TITLE
Bulk editing records

### ISSUE THREAD

**Issue by fabricat** [auroraresearchlab/netbox-dns#210]
Hello,
I am trying to _bulk edit_ multiple records, in order to change only the value of a custom field.
Unfortunately, when I click on `Apply` I get the following blocking alert:
`A valid IPv4 address is required for record type A.`

Isn't it expected to leave **empty fields unchanged**?

Moreover, I see that the **Type** field is always pre-selected as **A**, even if I am bulk editing records of different types.
This could lead to unwanted changes.

**Comment by peteeckel** [comment]
HI @fabricat, thanks, I can confirm this. The problem is that the default setting in the Bulk Edit form is `A`, while it should be `None` instead. 

As a workaround, please just remove the "A" by clicking on the "x" on the right side of the entry field when you bulk edit records - I did a quick test and if you null the field the error you described does not occur. I'll prepare a PR fixing the default. Possibly it is not a bad idea to remove the option of bulk editing record types altogether, as that rarely makes any sense.
