### ISSUE TITLE
Add quick search to zone records tabs

### ISSUE THREAD

**Issue by mikat-gh** [auroraresearchlab/netbox-dns#250]
Hi,

Can we have quick search in the zone records and managed records tabs?

There is quick search in the records page, but then I need to filter by zone first. Going via the zone page is more logical way for me.

**Comment by peteeckel** [comment]
Hi @mikat-gh, I'll look into it ... should be possible, I think.

**Comment by peteeckel** [comment]
Hi, I had a look at this now. 

The Quick Search function is buried somewhere in the javascript innards of NetBox (a good starting point is `netbox/templates/inc/table_controls_htmx.html`). It's probably possible to extend the `ZoneRecordListView` and `ZoneManagedRecordListView` and the templates `zone_record.html` and 'zone_managed_record.html` of NetBox DNS so that the Quick Search field magically appears and works (I only managed the former :-)), but there's too much JavaScript involved for my taste, so I'm out.

If someone would like to pick this up it would be highly welcome - I would like to learn something and the functionality would be useful. But without someone joining in and helping I don't see a chance we get it in the forseeable future.

**Comment by peteeckel** [comment]
Good news, @mikat-gh!

The version that will support NetBox 3.4 will also have Quick Search in zone record/managed record lists. I could probably do it earlier as well, but I think it won't take too long.

**Comment by mikat-gh** [comment]
Great, thanks @peteeckel!

We can wait for this one, but is there a release planned with current fixes in master before requiring NetBox 3.4? Probably need to hold until 3.4.1 or .2 before upgrading production.
